const {Trail} = require('../models');

const trailData = [
    {
      id: 1,
      name: "Tingley Field",
      city: "Albuquerque",
      zip: 87102,
      crossstreets: "Coal and 10th SW",
      address: "10 Atlantic Ave SW",
      transit: "ABQ Ride Stops:  #53, #54",
      lat: "35.0772432",
      lng: "-106.6555564",
      desc: "This redeveloped park provides a catchment basin in monsoon season and the new recreation facilities and walking trail are great for the whole family.",
      lighting: "On trail and parking lot",
      difficulty: 1,
      surface: "6-foot+ wide sidewalk, 4-foot wide gravel on 2 sides",
      parking: "On site",
      facilities: "Restrooms",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450547549tingleyParkSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1455036748P1130010.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1455036748P1130010.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-09-30 11:55:21",
      reviews: 1,
      url: "https:\/\/prescriptiontrails.org\/trail\/1\/tingley-field\/"
    },
    {
      id: 2,
      name: "Tingley Beach",
      city: "Albuquerque",
      zip: 87104,
      crossstreets: "Central Ave. & Tingley Dr. SW",
      address: "1800 Tingley Drive SW",
      transit: "ABQ Ride Stops:  #66, Rapid Ride",
      lat: "35.086244",
      lng: "-106.674171",
      desc: "Tingley Beach is on the Rio Grande near downtown Albuquerque next to the BIOPark Zoo and Aquarium and offers fishing hiking model boat sailing wildlife viewing and walking trails around three ponds. For more information on events call 505-248-8514. Visit the city's a https://www.cabq.gov culturalservices biopark tingley fishing weekly-fishing-report Weekly Fishing Report for information on fishing.",
      lighting: "None",
      difficulty: 1,
      surface: "5-foot wide pavement",
      parking: "ADA accessible, ample parking on site",
      facilities: "Restrooms, bike racks",
      hours: "Dawn to dusk",
      loopcount: 3,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450551278tingleyBeachSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450551300tingly.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1450551300tingly.jpg",
      published: "true",
      rating: 4,
      ratings: 2,
      ModifiedTime: "2021-02-12 03:55:11",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/2\/tingley-beach\/"
    },
    {
      id: 3,
      name: "Tiguex Park",
      city: "Albuquerque",
      zip: 87104,
      crossstreets: "Mountain & Rio Grande NW",
      address: "1800 Mountain Rd NW",
      transit: "ABQ Ride Stops:  #36, bus stop on Rio Grande & Mountain - 235 steps to park",
      lat: "35.0967569",
      lng: "-106.66616",
      desc: "Walk two loop paths at Tiguex Park starting at 19th Street. The outer loop and inner loop connect at several points adding variety. The park is visible from the street and many people visit it.",
      lighting: "None",
      difficulty: 1,
      surface: "8-foot wide concrete",
      parking: "On street",
      facilities: "Picnic tables",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450551913tiguex-park.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450551924tiguex.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1450551924tiguex.jpg",
      published: "true",
      rating: 4,
      ratings: 2,
      ModifiedTime: "2021-04-13 20:46:37",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/3\/tiguex-park\/"
    },
    {
      id: 4,
      name: "Durand Open Space",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Isleta Blvd. & Metzgar Rd. SW",
      address: "4812 Isleta Blvd SW",
      transit: "Abq Ride Stop #53",
      lat: "35.001974",
      lng: "-106.689702",
      desc: "This trail around grain fields provides a relaxing and fun walk. The site is farmed for wildlife to attract birds and features a crossing to the bosque. Known by residents and pilots as the Patch, the landing strip and an adjoining hanger were used to conduct aircraft repair and restoration.  Following the closure of the landing strip in the 1970s the property reverted to agriculture.",
      lighting: "None",
      difficulty: 2,
      surface: "5-foot wide crusher fine",
      parking: "On site",
      facilities: "Benches",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450748639durandParkSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454876314Durand.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454876314Durand.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2020-04-02 11:17:33",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/4\/durand-open-space\/"
    },
    {
      id: 5,
      name: "Gutierrez-Hubbell Open Space",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Isleta Blvd. & Don Felipe Rd. SW",
      address: "6029 Isleta Blvd SW",
      transit: "ABQ Ride Stops:  #66, Rapid Ride",
      lat: "34.989444",
      lng: "-106.696689",
      desc: "Gutierrez-Hubbell House Open Space offers views of the farm and demonstration gardens on this historic site making this a pleasing walk. Many public events are offered throughout the year - call (505) 314-0400 for details.",
      lighting: "None",
      difficulty: 3,
      surface: "4-foot wide loose mulch or crusher fine",
      parking: "On site during open hours or along Hubbell",
      facilities: "Historic building",
      hours: "dawn to dusk",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450749461gutierrezHubbellSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1450749670CIMG6601.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1450749670CIMG6601.JPG.jpg",
      published: "true",
      rating: 3.5,
      ratings: 2,
      ModifiedTime: "2021-04-01 13:55:20",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/5\/gutierrez-hubbell-open-space\/"
    },
    {
      id: 6,
      name: "Pajarito Open Space",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Isleta Blvd. & Pajarito Rd. SW",
      address: "6001 Beck Rd SW",
      transit: "None",
      lat: "34.9919803",
      lng: "-106.7037313",
      desc: "A trail around the grain field and under the trees provides a relaxing and fun walk. Pajarito Open Space offers a beautiful view of the West Mesa and the large trees are ideal for bird watching. It is located at the southwest corner of Beck Rd. and Don Felipe Rd. The property was owned by the Beck family for many years and was a small family dairy farm with surrounding alfalfa fields. The property is surrounded by a mix of agricultural and residential development.",
      lighting: "None",
      difficulty: 2,
      surface: "6 - 10 foot wide crusher fine",
      parking: "On site",
      facilities: "None",
      hours: "Dawn to dusk",
      loopcount: 3,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451166291pajaritoSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451166297Pajarito.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1451166297Pajarito.jpg",
      published: "true",
      rating: 3.5,
      ratings: 2,
      ModifiedTime: "2020-04-02 11:16:21",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/6\/pajarito-open-space\/"
    },
    {
      id: 7,
      name: "Pat Hurley Park",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Yucca Rd & Central Ave. SW",
      address: "374 Yucca Dr NW",
      transit: "ABQ Ride Stops:  #66, #766",
      lat: "35.08923",
      lng: "-106.70056",
      desc: "Pat Hurley Park has two developed areas. They are connected by a paved path that winds up the hill. The lower loop circles the Community Center and playground. The upper loop circles grass playfields and a small playground. ",
      lighting: "None",
      difficulty: 1,
      surface: "4 to 6 feet wide concrete",
      parking: "Each developed area has accessible parking",
      facilities: "Resting areas, Benches",
      hours: "Dawn to dusk",
      loopcount: 3,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/145123344077b9ab7e-461c-40cc-8c7d-1a798b8344bf.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451233911PatHurley.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1451233911PatHurley.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2020-12-01 15:54:30",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/7\/pat-hurley-park\/"
    },
    {
      id: 8,
      name: "Rio Bravo Open Space",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Rio Bravo SW, east of the Rio Grande bridge. Access from Poco Loco Drive. No access from Rio Bravo.",
      address: "900 Rio Bravo Blvd SW",
      transit: "None",
      lat: "35.0272733",
      lng: "-106.6742199",
      desc: "This quiet shady trail loops under a canopy of cottonwoods in the bosque and brings you within view of the Rio Grande. It also provides access to the multi-use trails along the Atrisco Riverside Drain and Rio Bravo. Rio Bravo NE. east of the Rio Grande and north of the Rio Bravo Bridge.  Follow the signs for Rio Bravo Picnic area from Rio Bravo heading west from Second Street.  ",
      lighting: "None",
      difficulty: 1,
      surface: "6-foot wide hard packed gravel",
      parking: "Includes 2 wheel-chair concrete pads for easier access. Driving: go W on Rio Bravo 0.4 mi from Second Street.  The Picnic Area is on a frontage road that is 0.3 mi W after turning right off Rio Bravo.",
      facilities: "None",
      hours: "7 a.m. to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451245353rio-bravo-sat.jpg",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451245368riobravo.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1451245368riobravo.jpg",
      published: "true",
      rating: 3.5,
      ratings: 2,
      ModifiedTime: "2020-04-01 13:26:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/8\/rio-bravo-open-space\/"
    },
    {
      id: 9,
      name: "Sanchez Farm Open Space",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Isleta Blvd & Arenal Rd SW",
      address: "1180 Arenal Rd SW",
      transit: "ABQ Ride Stops:  #53; bus stop on Isleta: 0.4 miles or 845 steps to park",
      lat: "35.050203",
      lng: "-106.670998",
      desc: "Enjoy this Open Space in the South Valley viewing the farming plots and wildlife. Enter the site at the pedestrian gate near the acequia. Public events are offered throughout the year. For information about events call 314-0400. This property was historically agricultural owned and farmed by the Sanchez family for more than 300 years before the county's Public Works division purchased it to serve as a storm drainage facility.",
      lighting: "None",
      difficulty: 3,
      surface: "dirt and gravel",
      parking: "On Arenal Rd",
      facilities: "None",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451330582sanchezFarmSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451330593sanchezFarm.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1451330593sanchezFarm.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-03-04 13:30:42",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/9\/sanchez-farm-open-space\/"
    },
    {
      id: 10,
      name: "Valle Del Bosque Park",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Sunset Rd between Central and Bridge",
      address: "480 Sunset Rd SW",
      transit: "None",
      lat: "35.075152",
      lng: "-106.674463",
      desc: "Located in a quiet neighborhood this park has a play area. It is adjacent to the Rio Grande Bosque and provides access to the Rio Grande Valley State Park with an overlook above the river.",
      lighting: "None",
      difficulty: 2,
      surface: "10-foot wide concrete, asphalt, and crusher fine",
      parking: "On site",
      facilities: "None",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451331016valle-del-bosque-sat.jpg",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/14513312524731-cover.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_14513312524731-cover.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/10\/valle-del-bosque-park\/"
    },
    {
      id: 11,
      name: "Westside Community Center",
      city: "Albuquerque",
      zip: 87105,
      crossstreets: "Isleta & Arenal SW",
      address: "1250 Isleta Blvd SW",
      transit: "ABQ Ride Stop:  #53",
      lat: "35.0537822",
      lng: "-106.672675",
      desc: "In 1959 Westside Community Center was the first community center built by Bernalillo County Parks and Recreation. During its 54-year history several renovations have been completed including a new gym and fitness center. There is also a 1 3 mile paved walking trail that circles the center and the front park. Visit the Center's a https://www.bernco.gov community-services westside.aspx website for more information.",
      lighting: "None",
      difficulty: 2,
      surface: "5-foot wide packed dirt",
      parking: "On site",
      facilities: "Community Center",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1451334750westside-community-complex-sat.jpg",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453474881unspecified.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1451334751Westside_CC.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/11\/westside-community-center\/"
    },
    {
      id: 15,
      name: "Bataan Park",
      city: "Albuquerque",
      zip: 87106,
      crossstreets: "Lomas & Carlisle NE",
      address: "3499 Lomas Blvd NE",
      transit: "ABQ Ride Stops:  #5, #11",
      lat: "35.0875462",
      lng: "-106.6054749",
      desc: "Bataan Park is located in the lower NE Heights. The trail is tree-lined and there is a large open space towards one end making it a great place to picnic. Bataan park is close to UNM Nob Hill and not far from Altura Park.",
      lighting: "None",
      difficulty: 2,
      surface: "6-foot wide concrete or packed gravel",
      parking: "On street",
      facilities: "Drugstore, other shops nearby",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1452722166bataan-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/14527219272014-04-25.png",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_14527219272014-04-25.jpg",
      published: "true",
      rating: 4.5,
      ratings: 2,
      ModifiedTime: "2020-04-02 11:19:15",
      reviews: 1,
      url: "https:\/\/prescriptiontrails.org\/trail\/15\/bataan-park\/"
    },
    {
      id: 16,
      name: "Roosevelt Park",
      city: "Albuquerque",
      zip: 87106,
      crossstreets: "Coal & University SE",
      address: "500 Spruce St SE",
      transit: "#97; Coal & Cedar: 145 steps; Univeristy & Coal: 1,584 steps to park",
      lat: "35.0755898",
      lng: "-106.6309911",
      desc: "This redeveloped park offers a flat trail segment on the north. The southern half is quite steep. The park is newly renovated. There are a lot of tree-shaded areas. Dogs are permitted off-leash. There is a lot of activity.  ",
      lighting: "None",
      difficulty: 2,
      surface: "4-6 foot wide concrete and packed gravel",
      parking: "Parking lot near Hazeldine and Sycamore SE",
      facilities: "None",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453068183roosevelt-park-sat-1.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453068189Albuquerque_Roosevelt_Park.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453068189Albuquerque_Roosevelt_Park.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-10-10 15:23:03",
      reviews: 1,
      url: "https:\/\/prescriptiontrails.org\/trail\/16\/roosevelt-park\/"
    },
    {
      id: 17,
      name: "Summit Park",
      city: "Albuquerque",
      zip: 87106,
      crossstreets: "Girard & Constitution NE",
      address: "3000 Constitution NE",
      transit: "#12; bus stop on Bryn Mawr & Constitution",
      lat: "35.094321",
      lng: "-106.610852",
      desc: "Summit Park is a community park located in a quiet neighborhood setting with shade trees.",
      lighting: "None",
      difficulty: 1,
      surface: "4.5-foot wide concrete",
      parking: "On street",
      facilities: "None",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453068349summitParkSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453666942SV300022.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453666942SV300022.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-09-26 10:10:45",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/17\/summit-park\/"
    },
    {
      id: 18,
      name: "Alameda Drain Trail ",
      city: "Albuquerque",
      zip: 87107,
      crossstreets: "12th Street & Matthew NW",
      address: " 12th St NW & Matthew Ave NW",
      transit: "#36",
      lat: "35.1181939",
      lng: "-106.6564454",
      desc: "The trail runs along the south side of the Alameda Drain. Access Alameda Drain Trail across bridges near Garfield Park or Matthew Meadows Park. Caution Street crossings are not pedestrian friendly and bridges are not handicap accessible.",
      lighting: "None",
      difficulty: 1,
      surface: "8-12 foot wide asphalt",
      parking: "At Garfield Park or on street at Matthew Meadows Park",
      facilities: "None",
      hours: "Open",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453068423alameda-trail-drain-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454903106alameda.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454903106alameda.jpg",
      published: "true",
      rating: 3.85715,
      ratings: 7,
      ModifiedTime: "2020-04-01 13:26:57",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/18\/alameda-drain-trail\/"
    },
    {
      id: 19,
      name: "Aldo Leopold Trail",
      city: "Albuquerque",
      zip: 87107,
      crossstreets: "Candelaria & Rio Grande Blvd NW",
      address: "Candelaria & Rio Grande Blvd NW",
      transit: "#36",
      lat: "35.125096",
      lng: "-106.6738396",
      desc: "Accessed through Rio Grande Nature Center State Park the trail starts at the center's west gate. Cross the bridge and climb the hill to your right. At the top of the levee cross the multi-use Paseo del Bosque trail. After hours the trail can be accessed from the multi-use trail at the end of Candelaria. Access free from Paseo del Bosque trail.",
      lighting: "None",
      difficulty: 1,
      surface: "6-8 foot wide asphalt",
      parking: "An entrance fee is required, or bring your ‘walking prescription’ to the Visitor Center, and NM State Parks will issue a six month free pass.",
      facilities: "Visitor Center",
      hours: "6 a.m. to 10 p.m",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453068527aldo-leopold-trail-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1475595595Unknown.jpeg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1475595595Unknown.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2021-04-01 13:58:37",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/19\/aldo-leopold-trail\/"
    },
    {
      id: 20,
      name: "Hartnett Park",
      city: "Albuquerque",
      zip: 87107,
      crossstreets: "Rio Grande Blvd. & Chavez NW",
      address: "6718 Rio Grande Blvd NW Albuquerque, NM 87107",
      transit: "None",
      lat: "35.1591825",
      lng: "-106.6542452",
      desc: "Hartnett Park is located at the Los Ranchos Village Hall. Walk past the playground along the irrigation ditch and around the community barn. This is a busy place on Saturday mornings when the Growers Market is active.",
      lighting: "None",
      difficulty: 1,
      surface: "8-foot wide asphalt",
      parking: "On site",
      facilities: "Daytime hours",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453067791hartnettParkSat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454902259Hartnett.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454902259Hartnett.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2021-04-01 13:59:46",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/20\/hartnett-park\/"
    },
    {
      id: 21,
      name: "Los Poblanos Open Space",
      city: "Albuquerque",
      zip: 87107,
      crossstreets: "Montano & Rio Grande Blvd. NW but access is easier from 4th St then west to site",
      address: "Montano & Rio Grande Blvd. NW",
      transit: "unavailable",
      lat: "35.1359657",
      lng: "-106.6692826",
      desc: "Visit the site of the annual Harvest Festival and Maize Maze. Be sure to check out the community garden maintained by Rio Grande Community Farm Enter from Montano Boulevard or from Alvarado Elementary School Solar Nabor on the north side.",
      lighting: "None",
      difficulty: 3,
      surface: "Wide natural farm roads, ditch banks",
      parking: "On street",
      facilities: "Pet waste receptables",
      hours: "7 a.m. to dusk",
      loopcount: 4,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453068710los-poblanos-open-space-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453672133CIMGd3962.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453672133CIMGd3962.jpg",
      published: "true",
      rating: 5,
      ratings: 1,
      ModifiedTime: "2019-06-11 16:31:23",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/21\/los-poblanos-open-space\/"
    },
    {
      id: 22,
      name: "Highland High School Track",
      city: "Albuquerque",
      zip: 87108,
      crossstreets: "Washington & Lead SE",
      address: "4700 Coal Ave SE",
      transit: "ABQ Ride Stops:  #97; Zuni & Adams 0.2 miles or 475 steps to track",
      lat: "35.0745148",
      lng: "-106.5911943",
      desc: "There are many regular walkers on the track. Avoid use during school hours. Consider other school tracks for walking after school hours and on weekends.",
      lighting: "None",
      difficulty: 1,
      surface: "Cushioned track surface",
      parking: "Highland Pool parking lot, east side of Jackson St.",
      facilities: "None",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1452877810highland-high-school-track-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1452877950Highland_High_School-Albuquerque.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1452877950Highland_High_School-Albuquerque.jpg",
      published: "true",
      rating: 4,
      ratings: 2,
      ModifiedTime: "2019-10-11 15:49:41",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/22\/highland-high-school-track\/"
    },
    {
      id: 23,
      name: "Mesa Verde Park",
      city: "Albuquerque",
      zip: 87108,
      crossstreets: "Pennsylvania & Marquette NE",
      address: "7900 Marquette Ave NE",
      transit: "#11; Lomas & Pennsylvania then 0.5 miles or 1,056 steps to park",
      lat: "35.082768",
      lng: "-106.558043",
      desc: "Starting your walk at the handicap accessible parking lot of the Mesa Verde Community Center more than half a mile of trail encompasses an abundance of outdoor activities and sites. Wheelchair accessible ramps are also located at the street corners of the park.",
      lighting: "None",
      difficulty: 1,
      surface: "4 foot wide concrete sidewalk",
      parking: "Mesa Verde Community Center",
      facilities: "Mesa Verde Community Center",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453330134mesa-verde-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1475527479IMG_1901.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1475527479IMG_1901.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-10-11 15:51:11",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/23\/mesa-verde-park\/"
    },
    {
      id: 24,
      name: "Phil Chacon Park",
      city: "Albuquerque",
      zip: 87108,
      crossstreets: "Louisiana & Kathryn SE",
      address: "7600 Southern Ave SE",
      transit: "#3 & #157",
      lat: "35.0671462",
      lng: "-106.5643102",
      desc: "Home to one of many Public Art installations in Albuquerque Phil Chacon Park encompasses a dedicated statue ready access to additional trails leading to the New Mexico Veterans Memorial Park and soccer rugby fields.",
      lighting: "None",
      difficulty: 2,
      surface: "4 - 8 foot wide asphalt and packed gravel",
      parking: "Cesar Chavez Community Center",
      facilities: "Cesar Chavez Community Center",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453331127phil-chacon-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1455463562IMG_1124.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1455463562IMG_1124.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-10-11 15:49:32",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/24\/phil-chacon-park\/"
    },
    {
      id: 25,
      name: "Arroyo Del Oso Park",
      city: "Albuquerque",
      zip: 87109,
      crossstreets: "Wyoming & Spain NE",
      address: "7001 Osuna Rd NE",
      transit: "ABQ Ride Stop: #31",
      lat: "35.1393168",
      lng: "-106.5690814",
      desc: "With the primary path encircling the soccer fields this park is a hotspot of activity during the summer months. An additional playground is located at the Southwest corner of the park with parking potentially limited by sporting events in the fall and spring.",
      lighting: "None",
      difficulty: 1,
      surface: "4 - 6 foot wide concrete",
      parking: "On site",
      facilities: "Possible portable restrooms",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453332005arroyo-del-oso-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/145490237587109ArroyoDelOso.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_145490237587109ArroyoDelOso.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2021-04-01 14:00:23",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/25\/arroyo-del-oso-park\/"
    },
    {
      id: 26,
      name: "Heritage Hills Park",
      city: "Albuquerque",
      zip: 87109,
      crossstreets: "Ventura & Harper NE",
      address: "7015 Ventura Ave NE",
      transit: "ABQ Ride Stops: #31, #91, #2",
      lat: "35.160183",
      lng: "-106.545576",
      desc: "Being highly visible from the street Heritage Hills Park also known as North Pino Arroyo Trail offers tremendous views of the volcanoes Mount Taylor and the Sandia Mountains.",
      lighting: "None",
      difficulty: 1,
      surface: "8 foot wide asphalt",
      parking: "On site",
      facilities: "Cherry Hills Library at West end",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453332960heritage-hills-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1455462295IMG_1084.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1455462295IMG_1084.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2021-04-01 14:00:45",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/26\/heritage-hills-park\/"
    },
    {
      id: 27,
      name: "Loma Del Norte Park",
      city: "Albuquerque",
      zip: 87109,
      crossstreets: "Loma del Norte & Wyoming Blvd NE",
      address: "7898 Raymond Dr NE",
      transit: "ABQ Ride Stop: #31",
      lat: "35.1658573",
      lng: "-106.5614989",
      desc: "Being described as a hidden gem this park offers a number of amenities including sports fields playgrounds and being pet friendly. The trail itself begins at the Southwest corner of the park and winds through the interior of the space offering great visibility of other activities and people.",
      lighting: "None",
      difficulty: 1,
      surface: "4 - 6 foot wide concrete",
      parking: "On street",
      facilities: "None",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453333863loma-del-norte-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/145490246487109LomaDelNorte.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_145490246487109LomaDelNorte.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/27\/loma-del-norte-park\/"
    },
    {
      id: 28,
      name: "North Domingo Baca Park",
      city: "Albuquerque",
      zip: 87109,
      crossstreets: "Wyoming & Paseo de Norte Blvd NE",
      address: "7521 Carmel NE",
      transit: "ABQ Ride Stop: #31",
      lat: "35.1777204",
      lng: "-106.5609613",
      desc: "North Domingo Baca Park includes ammenities and nearby shopping for just about every occasion. Ranging from a comprehensive Multigenerational Center to a skate park and leash-free dog areas North Domingo Baca is a fantastic outdoor space for everyone. ",
      lighting: "None",
      difficulty: 2,
      surface: "4 - 6 foot wide paved sidewalk; gravel",
      parking: "North side",
      facilities: "Multigenerational Center; Police and fire stations on site",
      hours: "6 a.m. to 10 p.m.",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453489163north-domingo-baca-sat.jpg",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453667241SV300034.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453667241SV300034.jpg",
      published: "true",
      rating: 5,
      ratings: 1,
      ModifiedTime: "2020-06-29 17:09:30",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/28\/north-domingo-baca-park\/"
    },
    {
      id: 29,
      name: "Altura Park",
      city: "Albuquerque",
      zip: 87110,
      crossstreets: "Indian School & Washington NE",
      address: "Altura Park",
      transit: "ABQ Ride Stop: #6",
      lat: "35.0984067",
      lng: "-106.5981861",
      desc: "Located in one of the quieter neighborhoods in central Albuquerque this park offers open spaces tennis courts and a walking path lined with trees.",
      lighting: "None",
      difficulty: 3,
      surface: "4 foot wide concrete or grass path",
      parking: "On street",
      facilities: "None",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453491773altura-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1455463451IMG_1128.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1455463451IMG_1128.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-06-11 16:32:31",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/29\/altura-park\/"
    },
    {
      id: 30,
      name: "Bel-Air Miramontes park",
      city: "Albuquerque",
      zip: 87110,
      crossstreets: "Carlisle & Menaul Blvd NE",
      address: "Bel-Air Miramontes",
      transit: "ABQ Ride Stops: #5, #8",
      lat: "35.1009909",
      lng: "-106.5701927",
      desc: "With a playground and good visibility throughout this park offers a combination of interconnected walking trails to allow the user to add some variety to their exercise.",
      lighting: "None",
      difficulty: 1,
      surface: "6 foot wide concrete",
      parking: "Accessible parking on Phoenix Ave",
      facilities: "Businesses on Menaul",
      hours: "6 a.m - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453493123bel-air-miramontes-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1455463382IMG_1142.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1455463382IMG_1142.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/30\/bel-air-miramontes-park\/"
    },
    {
      id: 31,
      name: "Jerry Cline Park",
      city: "Albuquerque",
      zip: 87110,
      crossstreets: "Constitution & Louisiana NE",
      address: "7001 Constitution Ave NE",
      transit: "ABQ Ride Stops: #3, #766",
      lat: "35.0951809",
      lng: "-106.567168",
      desc: "This park's main trail loops around the soccer field tennis courts and playground. While being a great walking area it additionally offers access to nearby areas such as the multi-use Paseo de las Montanas trail and the Tom Bolack Urban Forest and Dog Park.",
      lighting: "None",
      difficulty: 2,
      surface: "4 - 6 foot wide crusher fine",
      parking: "On site",
      facilities: "Restrooms near tennis courts",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454638922jerry-cline-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454638894jc.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454638894jc.JPG.jpg",
      published: "true",
      rating: 5,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/31\/jerry-cline-park\/"
    },
    {
      id: 32,
      name: "Montgomery Park",
      city: "Albuquerque",
      zip: 87110,
      crossstreets: "Commanche & San Mateo NE",
      address: "5510 Ponderosa NE & San Mateo",
      transit: "ABQ Ride Stop: #141",
      lat: "35.1254701",
      lng: "-106.5865393",
      desc: "Located near one of Albuquerque's many public libraries this path starts here and continues clockwise around the park perimeter. With the first segment using the Paseo del Noreste multi-use trail it offers great access to other areas in central Albuquerque. Additionally the path is steep for a short segment near Comanche Boulevard.",
      lighting: "None",
      difficulty: 1,
      surface: "4 - 8 foot wide asphalt\/concrete",
      parking: "On site",
      facilities: "Erna Ferguson Library; Palo Duro Senior Center; Montgomery Pool",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453495253montgomery-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454903639Montd.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454903639Montd.jpg",
      published: "true",
      rating: 5,
      ratings: 1,
      ModifiedTime: "2021-04-01 14:03:09",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/32\/montgomery-park\/"
    },
    {
      id: 33,
      name: "Stardust Skies Park",
      city: "Albuquerque",
      zip: 87110,
      crossstreets: "Pennsylvania & Montgomery Blvd NE",
      address: "4301 Pennsylvania NE",
      transit: "ABQ Ride Stop: #5; Montgomery & Pennsylvania 0.5 mile or 1,056 steps to park",
      lat: "35.0900554",
      lng: "-106.5594672",
      desc: "",
      lighting: "2 lights",
      difficulty: 2,
      surface: "5 foot wide hard-packed gravel or 4 foot wide concrete",
      parking: "On street",
      facilities: "None",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453496198stardust-skies-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/145490254887110Stardust.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_145490254887110Stardust.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/33\/stardust-skies-park\/"
    },
    {
      id: 34,
      name: "Academy Hills Park",
      city: "Albuquerque",
      zip: 87111,
      crossstreets: "Juan Tabo & Eubank NE",
      address: "9709 Layton NE",
      transit: "ABQ Ride Stops: #1, #2",
      lat: "35.147601",
      lng: "-106.532229",
      desc: "With continued improvements happening at this and other parks around Albuquerque Academy Hills remains a great area to walk jog and enjoy. Continued use by people utilizing the shaded structure sports fields and dog-friendly path is only going to get better as the City of Abq installs new walking paths and amenities. ",
      lighting: "None",
      difficulty: 3,
      surface: "1 - 2 foot wide natural path on grass; some 3.5 - foot wide concrete",
      parking: "On street",
      facilities: "Shopping center across Eubank Blvd",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453497011academy-hills-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/145490263087111AcademyHills.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_145490263087111AcademyHills.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2017-03-16 20:03:01",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/34\/academy-hills-park\/"
    },
    {
      id: 35,
      name: "El Oso Grande Park",
      city: "Albuquerque",
      zip: 87111,
      crossstreets: "Morris & Osuna NE",
      address: "10600 Osuna  NE",
      transit: "None",
      lat: "35.136608",
      lng: "-106.521033",
      desc: "This park offers a primary trail that follows the perimeter of the sports fields offering excellent visibility to walkers and joggers. For the more adventurous at heart it also acts as the starting point to the 4-mile long Bear Canyon Trail taking the user through great New Mexico landscapes and ending at the base of the mountain near the foothills area.",
      lighting: "None",
      difficulty: 1,
      surface: "4 - 6 foot wide concrete\/asphalt",
      parking: "On site and along Osuna",
      facilities: "CNM campus south of the park",
      hours: "6 a.m. - 10 p.m",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454902881el-oso-grande-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/145490289287111ElOsoGrande.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_145490289287111ElOsoGrande.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2021-04-04 05:08:29",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/35\/el-oso-grande-park\/"
    },
    {
      id: 36,
      name: "Bianchetti Park",
      city: "Albuquerque",
      zip: 87112,
      crossstreets: "Lomas & Chelwood Park NE",
      address: "12910 Granite NE",
      transit: "ABQ Ride Stops: #11; Lomas & Chelwood Park 0.17 miles or 355 steps to park",
      lat: "35.0891318",
      lng: "-106.5036463",
      desc: "Bianchetti Park offers a unique combination of outdoor activity and alternative exercise. With a variation on typical climbing equipment offered in a public park this area allows for jogging walking and upper-body workouts.",
      lighting: "None",
      difficulty: 1,
      surface: "4 foot wide sidewalk with 4 foot packed gravel",
      parking: "On street",
      facilities: "Police station",
      hours: " 6 a.m. - 10 p.m",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453498281bianchetti-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454903224Bianchetti.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454903224Bianchetti.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-10-18 14:03:16",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/36\/bianchetti-park\/"
    },
    {
      id: 37,
      name: "Embudo Hills Park",
      city: "Albuquerque",
      zip: 87112,
      crossstreets: "Lomas & Monte Largo NE",
      address: "1200 Monte Verde NE",
      transit: "ABQ Ride Stop: #11 nearby",
      lat: "35.090473",
      lng: "-106.489312",
      desc: "Several choices exist for this loop. A connecting multi-use trail adds distance and challenge while Fitness stations on this World Trail Fitness Course are found along the linear path.",
      lighting: "None",
      difficulty: 2,
      surface: "6 foot asphalt or concrete",
      parking: "On street",
      facilities: "None",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453498772embudo-hills-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454903430Embudo.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454903430Embudo.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/37\/embudo-hills-park\/"
    },
    {
      id: 39,
      name: "Wildflower Park",
      city: "Albuquerque",
      zip: 87113,
      crossstreets: "San Mateo & Eagle Rock NE",
      address: "9011 San Mateo NE & Alameda",
      transit: "ABQ Ride Stops: #140, #141",
      lat: "35.1844167",
      lng: "-106.5864584",
      desc: "Balloon Fiesta fans will be able to take advantage of this park's great views and quiet demeanor. With multiple sports fields open spaces and walking trail Wildflower Park is a great place to get some exercise. The main path connects to another that crosses the arroyo in the Honeywell parking lot while the west end can be a bit steep.",
      lighting: "None",
      difficulty: 2,
      surface: "4 - 6 foot wide packed gravel",
      parking: "Parking lot on San Mateo",
      facilities: "None",
      hours: "6 a.m. - 10 p.m",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453500294wildflower-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454269246SV300019.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454269246SV300019.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/39\/wildflower-park\/"
    },
    {
      id: 40,
      name: "Black Arroyo Trail",
      city: "Albuquerque",
      zip: 87114,
      crossstreets: "Golf Course & McMahon NW",
      address: "Black Arroyo",
      transit: "ABQ Ride Stops: #92, #157",
      lat: "35.2149719",
      lng: "-106.6840305",
      desc: "This multi-use trail allows for great views of the New Mexico desert landscape by connecting the Salida del Sol and Hunter Run parks with a large asphalt walkway.",
      lighting: "none",
      difficulty: 2,
      surface: "8 - 12 foot wide asphalt",
      parking: "On street",
      facilities: "None",
      hours: "Open",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453501005black-arroyo-trail-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454269987SV300026.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454269987SV300026.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/40\/black-arroyo-trail\/"
    },
    {
      id: 41,
      name: "Paradise Hills Park",
      city: "Albuquerque",
      zip: 87114,
      crossstreets: "Paradise Hills & Park Lane NW",
      address: "5801 Paradise Blvd NW",
      transit: "None",
      lat: "35.1957598",
      lng: "-106.7113014",
      desc: "This trail around grain fields provides a relaxing and fun walk. The site is farmed for wildlife to attract birds and features a crossing to the bosque.",
      lighting: "None",
      difficulty: 2,
      surface: "4 - 8 foot wide crusher fine and concrete",
      parking: "North side",
      facilities: "Paradise Hills Community Center; public pools across the street; portable toilets; mutt-mitts; disposal receptacles",
      hours: "Dawn to Dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454270293paradise-hills-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454270258ParadiseHills02.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454270258ParadiseHills02.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/41\/paradise-hills-park\/"
    },
    {
      id: 42,
      name: "E. Atrisco\/West I-40 Trail",
      city: "Albuquerque",
      zip: 87120,
      crossstreets: "Coors & Ouray NW",
      address: "6324 Iliff Rd NW",
      transit: "None",
      lat: "35.1034193",
      lng: "-106.7150841",
      desc: "For easy access start your walk at East Atrisco Park near 68th St. and connect to the multi-use trail along the highway. To extend your walk check for new trails on this and the City of Abq website.",
      lighting: "None",
      difficulty: 1,
      surface: "Wide asphalt multi-use trail",
      parking: "On street and across the street on Iliff at Susie Rayos Marmon Elementary (after school hours and on weekends)",
      facilities: "None",
      hours: "Open",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453504037atrisco-i-40-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1455037078P3170012.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1455037078P3170012.JPG.jpg",
      published: "true",
      rating: 4.5,
      ratings: 2,
      ModifiedTime: "2018-04-19 04:12:17",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/42\/e-atrisco-west-i-40-trail\/"
    },
    {
      id: 43,
      name: "Mariposa Basin Park",
      city: "Albuquerque",
      zip: 87120,
      crossstreets: "Taylor Ranch Road & Kachina NW",
      address: "6701 Taylor Ranch  NW",
      transit: "ABQ Ride Stops: #92, #157",
      lat: "35.1608828",
      lng: "-106.6940513",
      desc: "This park offers three trail loops great views and access to playground equipment and a baseball field. Start by walking past the duck ponds and gradually climb to the top of the hill watching for loose sand and uneven asphalt as the trail begins. If you take Loop 1 the path returning to the play area is steep.",
      lighting: "None",
      difficulty: 2,
      surface: "4 - 6 foot wide asphalt, some hard-packed dirt",
      parking: "On site",
      facilities: "Portable restrooms; Don Newton Community Center south of the park",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453504672mariposa-basin-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454271370mpbasin.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454271370mpbasin.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-11-11 12:29:18",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/43\/mariposa-basin-park\/"
    },
    {
      id: 44,
      name: "Nusenda Credit Union Stadium",
      city: "Albuquerque",
      zip: 87120,
      crossstreets: "I-40 & 98th Street",
      address: "1601 Arroyo Vista Blvd NW",
      transit: "ABQ Ride Stop: #94 Unser Communter",
      lat: "35.0934379",
      lng: "-106.7587534",
      desc: "The Community Stadium is the newest member of the Albuquerque Public Schools APS Athletics family of district facilities. The stadium hosts APS football track and field as well as other athletic and community events. Featuring a large grass infield and an eight-lane track this stadium is perfect for both the seasoned athlete and someone new to the realm of exercise alike.",
      lighting: "Limited",
      difficulty: 1,
      surface: "4 foot wide cement surface & standard track material",
      parking: "Onsite parking open during athletic and community events; street parking at north end of stadium",
      facilities: "Available only during athletic or community events",
      hours: "Limited",
      loopcount: 3,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453505692nusendacommunitystadiumMap.jpg",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453677541795776_orig.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453677541795776_orig.jpg",
      published: "true",
      rating: 5,
      ratings: 1,
      ModifiedTime: "2018-07-30 12:52:22",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/44\/nusenda-credit-union-stadium\/"
    },
    {
      id: 45,
      name: "Open Space Visitor Center",
      city: "Albuquerque",
      zip: 87120,
      crossstreets: "Coors & Bosque Meadows Rd NW",
      address: "6500 Coors NW",
      transit: "ABQ Ride Stops: #155; Coors stop: 0.3 miles or 697 steps to park",
      lat: "35.165185",
      lng: "-106.673097",
      desc: "The Open Space Visitor Center offers the public information and resources on the Open Space program. The Visitor Center has exhibits interpreting the amazing natural and cultural resources Open Space protects. It also features an art gallery agricultural fields and a wetland marsh that draw a variety of wildlife and stunning views of the Sandia Mountains.",
      lighting: "None",
      difficulty: 3,
      surface: "4 - 6 foot wide crusher fine, concrete, and hard-packed dirt (some soft, sandy areas may exist)",
      parking: "ADA accessible, ample parking on site",
      facilities: "Restrooms; water fountain",
      hours: "Tues. - Sun. 9 a.m. to 5 p.m.; closed Monday",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453506272open-space-visitor-center-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1475773722Unknown.jpeg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1475773722Unknown.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2017-02-11 11:04:12",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/45\/open-space-visitor-center\/"
    },
    {
      id: 46,
      name: "Pueblo Montaño and Bosque Loop",
      city: "Albuquerque",
      zip: 87120,
      crossstreets: "Montaño & Coors Rd NW",
      address: "Pueblo Montaño and Bosque Loop",
      transit: "ABQ Ride Stops: #790, #155, #3\/157",
      lat: "35.1589536",
      lng: "-106.6777674",
      desc: "This multi-use recreational facility provides westside access to the bosque trail system dedicated ADA and equestrian parking areas and an ADA-accessible picnic area with interpretive educational signage. Enjoy a virtual tour of the Pueblo Montano chainsaw sculptures at their website.",
      lighting: "None",
      difficulty: 3,
      surface: "6 - 8 foot wide concrete with adjacent dirt path loop",
      parking: "On site",
      facilities: "Shopping area nearby",
      hours: "April - Oct. 7 a.m. to 9 p.m. Nov. - March 7 a.m. to 7 p.m.",
      loopcount: 2,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453506710pueblo-montano-bosque-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454609974Picnic-Area.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454609974Picnic-Area.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-10-07 20:19:27",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/46\/pueblo-montao-and-bosque-loop\/"
    },
    {
      id: 48,
      name: "Bachechi Open Space",
      city: "Albuquerque",
      zip: 87114,
      crossstreets: "Alameda & South Rio Grande Blvd NW",
      address: "9521 Rio Grande Blvd NW",
      transit: "None",
      lat: "35.194913",
      lng: "-106.639524",
      desc: "This North Valley historical setting now serves as an open space area in a natural environment. It is adjacent to the Rio Grande bosque and Rio Grande Valley State Park.",
      lighting: "None",
      difficulty: 2,
      surface: "3 to 6 foot wide crusher fine",
      parking: "South side of Alameda, includes equestrian parking",
      facilities: "Restrooms, pet mitts and disposal receptacles",
      hours: "Dawn to Dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453689708bachechi-open-space-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453689743IMG_1194.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453689743IMG_1194.JPG.jpg",
      published: "true",
      rating: 5,
      ratings: 2,
      ModifiedTime: "2021-01-06 12:28:12",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/48\/bachechi-open-space\/"
    },
    {
      id: 50,
      name: "Lazy Day Park",
      city: "Albuquerque",
      zip: 87121,
      crossstreets: "98th & Dennis Chavez SW",
      address: "3200 Lazy Day Dr SW ",
      transit: "None",
      lat: "35.026722",
      lng: "-106.737243",
      desc: "An additional walking path in the southeast corner of the park connects to the Dennis Chavez Blvd trails where you can add more steps to your walk.",
      lighting: "None",
      difficulty: 1,
      surface: "4-foot wide concrete",
      parking: "On street, west side of street",
      facilities: "None",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454268747lazy-day-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454268706SV300003.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454268706SV300003.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/50\/lazy-day-park\/"
    },
    {
      id: 51,
      name: "Westgate Community Center Park",
      city: "Albuquerque",
      zip: 87121,
      crossstreets: "Benavides & Snow Vista SW",
      address: "1400 Snow Vista SW ",
      transit: "#54",
      lat: "35.0522322",
      lng: "-106.7394078",
      desc: "The Center has a large classroom computer lab game room multipurpose room playground and park area for youth sports track and field events and outdoor recreation.",
      lighting: "None",
      difficulty: 1,
      surface: "5-foot wide asphalt",
      parking: "Community Center",
      facilities: "Community Center",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453933182westgate-community-center-park-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1453933408westgate-community-center-park-sat.png.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1453933408westgate-community-center-park-sat.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/51\/westgate-community-center-park\/"
    },
    {
      id: 52,
      name: "Ben Griener Soccer Field",
      city: "Albuquerque",
      zip: 87122,
      crossstreets: "Paseo del Norte & Eubank NE",
      address: "10900 Signal Avenue NE",
      transit: "None",
      lat: "35.1828087",
      lng: "-106.5190684",
      desc: "This Northeast Heights park also known for U.S. Senator Harrison H. Schmitt includes a soccer field that connects to a hang gliding field on a wide asphalt trail. Excellent views of the mountains and the city.",
      lighting: "None",
      difficulty: 3,
      surface: "10-foot wide asphalt; from Ben Greiner, trail connects to Hang Glider Park with a packed dirt trail",
      parking: "Paved parking area at soccer field; gravel parking area at hang glider park",
      facilities: "None",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454268872ben-griener-soccer-field-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454268876bg.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454268876bg.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2019-06-11 16:35:48",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/52\/ben-griener-soccer-field\/"
    },
    {
      id: 58,
      name: "Manzano Mesa Center",
      city: "Albuquerque",
      zip: 87123,
      crossstreets: "Eubank & Southern Blvd. SE",
      address: "501 Elizabeth St SE",
      transit: "ABQ Ride Stops:  #2",
      lat: "35.0659649",
      lng: "-106.5261078",
      desc: "Start this walk near the southeast corner of the Center. Travel along Southern Blvd. past the soccer field and turn left at the end of the fields. Activities at the Multigenerational Center are especially designed for seniors and youth and include everything you can find at a senior center as well as activities for youth ages six and up.",
      lighting: "None",
      difficulty: 1,
      surface: "6 foot wide concrete",
      parking: "On site",
      facilities: "Manzano Mesa Multi-Generational Center",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454639456manzano-mesa-multigenerational-center-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454639460manzanomesa.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454639460manzanomesa.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2017-03-16 20:03:47",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/58\/manzano-mesa-center\/"
    },
    {
      id: 63,
      name: "Elena Gallegos Cottonwood Springs Trail",
      city: "Albuquerque",
      zip: 87122,
      crossstreets: "Sims Park Road & Tramway Blvd. NE",
      address: "7100 Tramway Boulevard Northeast",
      transit: "None",
      lat: "35.164768",
      lng: "-106.471670",
      desc: "The Elena Gallegos Cottonwood Springs Trail is an ADA-accessible trail located in the foothills of the Sandia mountains at the Elena Gallegos Open Space Park. Visitors can enjoy many activities below the backdrop of the Sandia Mountains. The 640-acre park is a gem in the Open Space system. The Cottonwood Springs Trail provides great nature viewing at the wetland nature blind. If you wish to venture further there are many additional trails available. There is an entrance fee to access trail.",
      lighting: "None",
      difficulty: 1,
      surface: "6-foot wide concrete",
      parking: "On site; limited parking during weekends and events",
      facilities: "Restrooms, water fountain",
      hours: "Nov. - Mar. 7 a.m. to 7 p.m. April - Oct. 7 a.m. to 9 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454645092elena-gallegos-trail-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/14546452162013-09-16184328-0-orig-0.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_14546452162013-09-16184328-0-orig-0.jpg",
      published: "true",
      rating: 5,
      ratings: 1,
      ModifiedTime: "2021-04-04 05:08:07",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/63\/elena-gallegos-cottonwood-springs-trail\/"
    },
    {
      id: 64,
      name: "Noreste Park Trail",
      city: "Albuquerque",
      zip: 87122,
      crossstreets: "Wyoming & Eagle Rock NE",
      address: "8209 Oakland Avenue NE",
      transit: "#31",
      lat: "35.185982",
      lng: "-106.552897",
      desc: "Enjoy this multi-use trail along the La Cueva Arroyo in residential Albuquerque. ",
      lighting: "None",
      difficulty: 2,
      surface: "5-foot wide concrete",
      parking: "On street",
      facilities: "None",
      hours: "6 a.m. - 10 p.m.",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454646761noreste-park-trail-sat.png",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1454646968noreste.JPG",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1454646968noreste.JPG.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2016-02-25 01:14:00",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/64\/noreste-park-trail\/"
    },
    {
      id: 65,
      name: "Patricia Cassidy Park",
      city: "Albuquerque",
      zip: 87122,
      crossstreets: "Lowell St. & Summer Wind Pl. NE",
      address: "11900 Summer Wind Place NE ",
      transit: "None",
      lat: "35.1819607",
      lng: "-106.5069633",
      desc: "This small neighborhood park is located next to Double Eagle Elementary School and is a quiet setting for a walk. Be sure to check out the Little Free Library located in the park. ",
      lighting: "None",
      difficulty: 1,
      surface: " 6 - 8 foot wide asphalt and concrete",
      parking: "On street",
      facilities: "None",
      hours: "Dawn to dusk",
      loopcount: 1,
      satImgUrl: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1475527599IMG_1920.jpg",
      largeImgURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/1475527606IMG_1920.jpg",
      thumbURL: "https:\/\/prescriptiontrails.org\/admin\/new\/images\/square_1475527606IMG_1920.jpg",
      published: "true",
      rating: 3,
      ratings: 1,
      ModifiedTime: "2020-04-01 13:34:01",
      reviews: 0,
      url: "https:\/\/prescriptiontrails.org\/trail\/65\/patricia-cassidy-park\/"
    },

{
id: 70,
name: "Cabezon Park",
city: "Rio Rancho",
zip: 87144,
crossstreets: "Unser & Southern",
address: "2305 Cabezon Blvd SE",
transit: "Unavailable",
lat: "35.2323686",
lng: "-106.689955",
desc: "This large park has plenty of space for kids and pets to roam and explore Playground equipment is available for younger kids.",
lighting: "On street",
difficulty: 1,
surface: "Concrete 4 to 6 feet ",
parking: "On Site",
facilities: "Restrooms in Community Center, Water Fountains (open in Summer),  Swimming Pool (open in Summer)",
hours: "Dawn to dusk",
loopcount: 1,
satImgUrl: "https://prescriptiontrails.org/admin/new/images/1454795840cabezonsat.jpg",
largeImgURL: "https://prescriptiontrails.org/admin/new/images/1454795844NM_PUL_Cabezon_Park.jpg",
thumbURL: "https://prescriptiontrails.org/admin/new/images/square_1454795844NM_PUL_Cabezon_Park.jpg",
published: "true",
rating: 3,
ratings: 1,
ModifiedTime: "2018-07-07 16:10:04",
reviews: 0,
url: "https://prescriptiontrails.org/trail/70/cabezon-park/",
translations: "none"
},

{
id: 71,
name: "Chianti Park",
city: "Rio Rancho",
zip: 87124,
crossstreets: "Golf Course & Cabezon",
address: "1210 Chianti Rd SE",
transit: "Rio Rancho Transit: Buses #96 & #551 stop on Southern & Unser (weekdays only, peak times)",
lat: "35.2343979",
lng: "-106.6807299",
desc: "This park is situated next to a long walking path that travels through the nearby housing development.",
lighting: "None",
difficulty: 3,
surface: "Concrete, Asphalt and Packed Dirt, 4 feet wide",
parking: "On street",
facilities: "None",
hours: "Dawn to dusk",
loopcount: 1,
satImgUrl: "https://prescriptiontrails.org/admin/new/images/1454796195chianti.jpg",
largeImgURL: "https://prescriptiontrails.org/admin/new/images/1455651345IMG_0439.jpg",
thumbURL: "https://prescriptiontrails.org/admin/new/images/square_1455651345IMG_0439.jpg",
published: "true",
rating: 3,
ratings: 1,
ModifiedTime: "2018-07-23 13:53:57",
reviews: 0,
url: "https://prescriptiontrails.org/trail/71/chianti-park/",
translations: "none"
}
]

const seedTrails = () => Trail.bulkCreate(trailData);
module.exports = seedTrails;